name: .NetCore app to an azure wap

env:
  AZURE_WEBAPP_NAME: github-workflow-demo    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'             # set this to the path to your web app project, defaults to the repository root
  ROOT_PATH: './Project1.sln'     
  DOTNET_VERSION: '6.0.x'      
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-              

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.dotnet_root}}\myapp15
        working-directory: ${{env.root_path}}
     
      - name: Display folder file
        run: |
            echo "+++++++"
            cd ${{env.ROOT_PATH}}\myapp15
            dir        
